# Generated by Django 3.2.5 on 2021-07-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_nom', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
